openapi: 3.0.0
info:
  title: Sum of Distances
  contact: {}
  version: '1.0'
paths:
  /api/calculate-distance:
    post:
      summary: Calculate Sum of Two Distances
      description: Note! the distances array must have 2 elements only
      requestBody:
        required: true
        content:
          application/json:
            schema:
                type: object
                properties:
                  distances:
                    type: array
                    items:
                      type: object
                      properties:
                        value:
                          type: number
                        unit:
                          type: string
                  response_unit:
                    type: string
                    example: yard
                example:
                  distances:
                    - value: 1.3
                      unit: meter
                    - value: 1.2
                      unit: yard
                  response_unit: yard
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      value:
                        type: number
                      unit:
                        type: string
                    example:   # Sample object
                      value: 2.6217
                      unit: yard
